pub const QBZ_QCONNECT_TRANSPORT: &str = "QBZ_QCONNECT_TRANSPORT";
pub const QBZ_QCONNECT_QUEUE_MODEL: &str = "QBZ_QCONNECT_QUEUE_MODEL";
pub const QBZ_QCONNECT_STRICT_DOMAIN_ISOLATION: &str = "QBZ_QCONNECT_STRICT_DOMAIN_ISOLATION";
pub const QBZ_QCONNECT_PANEL_SWITCH: &str = "QBZ_QCONNECT_PANEL_SWITCH";
